version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  devicesapi:
    build:
      context: ./DevicesApi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=devicesdb;Username=postgres;Password=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./devices-client
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://devicesapi:5000/api
    depends_on:
      - devicesapi
